const keywords = [
	'kartik Bhalla',
	'kartik bhalla portfolio',
	'kartikbhalla12',
	'kbhalla12',
	'kartik bhalla dev',
	'kartik bhalla',
	'kartik dev',
	'bhalla dev',
	'Kartik',
	'Bhalla',
	'thedemon12',
	'kartikbhalla',
	'kartikbhalla.dev',
	'thedemon',
	"kartik's",
	"kartik bhalla's",
	"kartik bhalla's portfolio",
	"kartik's portfolio",
	'Kartik Bhalla Website',
	'upgrad',
	'upgrad abroad',
	'software developer upgrad',
	'software developer',
	'noida',
	'study abroad',
	'technology',
	'nsut',
	'netaji subhas university of technology',
	'netaji subhas university of technology east campus',
	'netaji subhas',
	'aiactr',
	'ait',
	'ambedkar institute',
	'ambedkar institute of advanced communication technologies and research',
	'nsut east campus',
	'east',
	'east campus',
	'training and placement',
	'placement coordinator',
	'tnp',
	'training',
	'placement',
	'react',
	'reactjs',
	'next',
	'nextjs',
	'New Delhi',
	'MERN Stack',
	'Full Stack Dev',
	'Full Stack Developer',
	'Cloud',
];

export default keywords;
