import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import Home from '../components/Home';

import { isMobile } from '../utils';

import styles from './index.module.scss';

interface LandingPageProps {
	isMobile: boolean;
}

const LandingPage: NextPage<LandingPageProps> = ({ isMobile }) => {
	const [isBlur, setIsBlur] = useState(false);
	const handleBlur = (blur: boolean) => {
		setIsBlur(blur);
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar isMobile={isMobile} onBlur={handleBlur} />

			<main className={`${styles.main} ${isBlur ? styles.blur : ''}`}>
				<Home isMobile={isMobile} />
				<Footer />
			</main>
		</div>
	);
};

export async function getServerSideProps(context: NextPageContext) {
	return {
		props: { isMobile: isMobile(context) },
	};
}

export default LandingPage;
